version: '3.8'

services:
  api:
    image: fastapi-backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"

  ui:
    image: gradio-ui
    container_name: gradio-ui
    ports:
      - "7860:7860"
    depends_on:
      - api
    environment:
      - API_HOST=http://api:8000
