services:
  api:
    image: remz01/fastapi-backend:latest
    container_name: fastapi-backend
    ports:
      - "8000:8000"

  ui:
    image: remz01/gradio-ui:latest
    container_name: gradio-ui
    ports:
      - "7860:7860"
    depends_on:
      - api
    environment:
      - API_HOST=http://api:8000
