name: Deploy to EC2 (Docker Compose)

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

env:
  DOCKERHUB_USER: remz01
  VERSION: ${{ vars.VERSION || 'latest' }}

jobs:
  deploy:
    runs-on: self-hosted  # Your EC2 is now the runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up working directory
        run: |
          cd ~
          if [ ! -d "logbert-structured-api" ]; then
            git clone https://github.com/rems8505/logbert-structured-api.git
          fi
          cd logbert-structured-api
          git pull origin main

      - name: Docker login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Docker images
        run: |
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/fastapi-backend:latest
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/gradio-ui:latest

      - name: Stop old containers
        run: |
          cd ~/logbert-structured-api
          sudo docker-compose down

      - name: Start new containers
        run: |
          cd ~/logbert-structured-api
          sudo docker-compose up -d --remove-orphans

      - name: ✅ Deployment Complete
        run: echo "Deployment to EC2 self-hosted runner completed successfully!"
