name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_OWNER: rems8505

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read VERSION file
        id: version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "Using version: $VERSION"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push FastAPI Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./api.Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_OWNER }}/logbert-fastapi:${{ env.VERSION }}
            ${{ env.IMAGE_OWNER }}/logbert-fastapi:latest

      - name: Build and push Gradio Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./ui.Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_OWNER }}/logbert-gradio:${{ env.VERSION }}
            ${{ env.IMAGE_OWNER }}/logbert-gradio:latest
