name: DockerHub Login Test

on:
  workflow_dispatch:

jobs:
  login-test:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
